### ISSUE TITLE
Timelion: Error: in cell #2: Unexpected type of argument in function quantileSeq

### ISSUE THREAD

**Issue by pavantummalapalli** [fermiumlabs/mathlion#29] opened 2016-10-20 09:40 UTC
Hi,

I am using the following formula in timelion

``` js
.es(index="pla*",metric=sum:requests).math("a=median(source);qal=quantileSeq(source,[0.05,0.95],true)").label("Requests") .value(1).math(a*source).label("Median") 
```

I am able to plot the median . how ever i am not able to plot the upper and lower quantiles.

I need to plot both 0.05 value and 0.95 value in the graph 

When i checked the  [QunatileSeq](http://mathlion.docs.fermiumlabs.com/en/latest/functions/quantileSeq/) , there is one scenario where we can return the two values.

Please help me in solving the above approach.

**Comment by SimoneTosato** [comment] 2016-10-20 09:50
The issue is with timelion itself probably, you can't plot an array of values so you need to plot the two quantiles separately. As soon as possible i will check if this is right and how to plot the two quantiles, a solution could be to plot 

```
.value(1).math("source*qal[1]") 
.value(1).math("source*qal[2]")
```

**Comment by ddavidebor** [comment] 2016-10-20 09:57
Also, isn't there a typo in `.math(asource)` ? If you want to just plot the variable `a` you can do:

``` js
.value(1).math(a)
.nop().math(a)  //a few keypress shorter
```

**Comment by ddavidebor** [comment] 2016-11-19 19:15
Hey @pavantummalapalli you still here?

**Comment by pavantummalapalli** [comment] 2016-11-20 05:04
yes.

**Comment by ddavidebor** [comment] 2016-11-20 11:38
@pavantummalapalli did the solution proposed by @SimoneTosato solved your issue?

**Comment by pavantummalapalli** [comment] 2016-11-20 11:54
No,

I have created in the following way where it returns single value instead of two values from above.
`qal=quantileSeq(source,0.05); qau=quantileSeq(source,0.95)`

**Comment by tobstarr** [comment] 2016-12-01 08:30
Just curious: is there a reason `quantileSeq` is not part of the offical documentation (at http://mathlion.docs.fermiumlabs.com/en/latest/)?

**Comment by ddavidebor** [comment] 2016-12-01 09:46
@tobstarr no, i think we removed it by accident. Thanks for the warning, I opened #31

**Comment by ddavidebor** [comment] 2016-12-01 09:51
@pavantummalapalli I'm closing the issue since I don't think we have a good way of avoiding your workaround. 

If course if someone would like to discuss the implementation and open a PR I'm all for it!

I have opened another one to fix the docs.

**Closed as completed by ddavidebor** 2016-12-01 09:51 UTC
Labels: bug
